const recoveryCurves = {
  Critical: {
    firstWeek: {
      medicineAdherence: { min: 70, max: 85 },
      physiotherapyAdherence: { min: 20, max: 35 },
      exerciseAdherence: { min: 10, max: 25 },
      appetite: "Poor",
      mood: "Low",
      sleep: { min: 4, max: 6 },
      bloodPressure: { systolicMin: 145, systolicMax: 170, diastolicMin: 90, diastolicMax: 105 },
      heartRate: { min: 85, max: 110 },
      oxygenSaturation: { min: 88, max: 94 },
      bloodSugar: { min: 130, max: 210 },
      physiotherapyAttendance: { min: 20, max: 35 },
      averageSessionDuration: { min: 10, max: 20 },
    },
    firstMonth: {
      medicineAdherence: { min: 75, max: 90 },
      physiotherapyAdherence: { min: 35, max: 50 },
      exerciseAdherence: { min: 20, max: 40 },
      appetite: "Low",
      mood: "Anxious",
      sleep: { min: 5, max: 7 },
      bloodPressure: { systolicMin: 135, systolicMax: 160, diastolicMin: 85, diastolicMax: 100 },
      heartRate: { min: 80, max: 100 },
      oxygenSaturation: { min: 90, max: 95 },
      bloodSugar: { min: 120, max: 190 },
      physiotherapyAttendance: { min: 35, max: 55 },
      averageSessionDuration: { min: 15, max: 25 },
    },
    sixMonths: {
      medicineAdherence: { min: 80, max: 92 },
      physiotherapyAdherence: { min: 45, max: 65 },
      exerciseAdherence: { min: 35, max: 55 },
      appetite: "Moderate",
      mood: "Stable",
      sleep: { min: 6, max: 8 },
      bloodPressure: { systolicMin: 130, systolicMax: 150, diastolicMin: 80, diastolicMax: 95 },
      heartRate: { min: 75, max: 95 },
      oxygenSaturation: { min: 92, max: 96 },
      bloodSugar: { min: 110, max: 170 },
      physiotherapyAttendance: { min: 50, max: 70 },
      averageSessionDuration: { min: 20, max: 35 },
    },
    oneYear: {
      medicineAdherence: { min: 82, max: 94 },
      physiotherapyAdherence: { min: 50, max: 70 },
      exerciseAdherence: { min: 40, max: 60 },
      appetite: "Moderate",
      mood: "Stable",
      sleep: { min: 6, max: 8 },
      bloodPressure: { systolicMin: 125, systolicMax: 145, diastolicMin: 78, diastolicMax: 92 },
      heartRate: { min: 72, max: 92 },
      oxygenSaturation: { min: 93, max: 97 },
      bloodSugar: { min: 100, max: 160 },
      physiotherapyAttendance: { min: 55, max: 75 },
      averageSessionDuration: { min: 25, max: 40 },
    },
  },
  Severe: {
    firstWeek: {
      medicineAdherence: { min: 75, max: 88 },
      physiotherapyAdherence: { min: 35, max: 50 },
      exerciseAdherence: { min: 25, max: 40 },
      appetite: "Low",
      mood: "Anxious",
      sleep: { min: 5, max: 7 },
      bloodPressure: { systolicMin: 140, systolicMax: 165, diastolicMin: 88, diastolicMax: 102 },
      heartRate: { min: 80, max: 105 },
      oxygenSaturation: { min: 91, max: 96 },
      bloodSugar: { min: 120, max: 195 },
      physiotherapyAttendance: { min: 35, max: 55 },
      averageSessionDuration: { min: 15, max: 25 },
    },
    firstMonth: {
      medicineAdherence: { min: 80, max: 92 },
      physiotherapyAdherence: { min: 50, max: 70 },
      exerciseAdherence: { min: 40, max: 60 },
      appetite: "Moderate",
      mood: "Stable",
      sleep: { min: 6, max: 8 },
      bloodPressure: { systolicMin: 130, systolicMax: 155, diastolicMin: 82, diastolicMax: 96 },
      heartRate: { min: 75, max: 98 },
      oxygenSaturation: { min: 93, max: 97 },
      bloodSugar: { min: 110, max: 175 },
      physiotherapyAttendance: { min: 55, max: 75 },
      averageSessionDuration: { min: 25, max: 40 },
    },
    sixMonths: {
      medicineAdherence: { min: 85, max: 95 },
      physiotherapyAdherence: { min: 65, max: 82 },
      exerciseAdherence: { min: 55, max: 75 },
      appetite: "Good",
      mood: "Improving",
      sleep: { min: 6, max: 8 },
      bloodPressure: { systolicMin: 122, systolicMax: 145, diastolicMin: 78, diastolicMax: 90 },
      heartRate: { min: 70, max: 90 },
      oxygenSaturation: { min: 95, max: 98 },
      bloodSugar: { min: 95, max: 155 },
      physiotherapyAttendance: { min: 70, max: 85 },
      averageSessionDuration: { min: 35, max: 50 },
    },
    oneYear: {
      medicineAdherence: { min: 88, max: 96 },
      physiotherapyAdherence: { min: 70, max: 88 },
      exerciseAdherence: { min: 60, max: 80 },
      appetite: "Good",
      mood: "Improving",
      sleep: { min: 7, max: 8 },
      bloodPressure: { systolicMin: 118, systolicMax: 140, diastolicMin: 75, diastolicMax: 88 },
      heartRate: { min: 68, max: 88 },
      oxygenSaturation: { min: 95, max: 99 },
      bloodSugar: { min: 90, max: 145 },
      physiotherapyAttendance: { min: 75, max: 90 },
      averageSessionDuration: { min: 40, max: 55 },
    },
  },
  Moderate: {
    firstWeek: {
      medicineAdherence: { min: 82, max: 92 },
      physiotherapyAdherence: { min: 55, max: 70 },
      exerciseAdherence: { min: 45, max: 65 },
      appetite: "Moderate",
      mood: "Stable",
      sleep: { min: 6, max: 8 },
      bloodPressure: { systolicMin: 128, systolicMax: 150, diastolicMin: 80, diastolicMax: 94 },
      heartRate: { min: 72, max: 95 },
      oxygenSaturation: { min: 94, max: 98 },
      bloodSugar: { min: 100, max: 170 },
      physiotherapyAttendance: { min: 55, max: 75 },
      averageSessionDuration: { min: 25, max: 40 },
    },
    firstMonth: {
      medicineAdherence: { min: 86, max: 95 },
      physiotherapyAdherence: { min: 70, max: 85 },
      exerciseAdherence: { min: 60, max: 78 },
      appetite: "Good",
      mood: "Improving",
      sleep: { min: 7, max: 8 },
      bloodPressure: { systolicMin: 120, systolicMax: 142, diastolicMin: 76, diastolicMax: 88 },
      heartRate: { min: 68, max: 88 },
      oxygenSaturation: { min: 96, max: 99 },
      bloodSugar: { min: 90, max: 150 },
      physiotherapyAttendance: { min: 72, max: 88 },
      averageSessionDuration: { min: 35, max: 50 },
    },
    sixMonths: {
      medicineAdherence: { min: 90, max: 97 },
      physiotherapyAdherence: { min: 80, max: 92 },
      exerciseAdherence: { min: 75, max: 90 },
      appetite: "Good",
      mood: "Positive",
      sleep: { min: 7, max: 9 },
      bloodPressure: { systolicMin: 115, systolicMax: 135, diastolicMin: 72, diastolicMax: 85 },
      heartRate: { min: 64, max: 84 },
      oxygenSaturation: { min: 97, max: 99 },
      bloodSugar: { min: 85, max: 135 },
      physiotherapyAttendance: { min: 82, max: 94 },
      averageSessionDuration: { min: 45, max: 60 },
    },
    oneYear: {
      medicineAdherence: { min: 92, max: 98 },
      physiotherapyAdherence: { min: 82, max: 95 },
      exerciseAdherence: { min: 78, max: 92 },
      appetite: "Good",
      mood: "Positive",
      sleep: { min: 7, max: 9 },
      bloodPressure: { systolicMin: 112, systolicMax: 132, diastolicMin: 70, diastolicMax: 84 },
      heartRate: { min: 62, max: 82 },
      oxygenSaturation: { min: 97, max: 99 },
      bloodSugar: { min: 82, max: 130 },
      physiotherapyAttendance: { min: 85, max: 96 },
      averageSessionDuration: { min: 45, max: 60 },
    },
  },
  Mild: {
    firstWeek: {
      medicineAdherence: { min: 88, max: 96 },
      physiotherapyAdherence: { min: 70, max: 85 },
      exerciseAdherence: { min: 65, max: 82 },
      appetite: "Good",
      mood: "Stable",
      sleep: { min: 7, max: 8 },
      bloodPressure: { systolicMin: 120, systolicMax: 140, diastolicMin: 75, diastolicMax: 88 },
      heartRate: { min: 66, max: 88 },
      oxygenSaturation: { min: 96, max: 99 },
      bloodSugar: { min: 88, max: 145 },
      physiotherapyAttendance: { min: 72, max: 88 },
      averageSessionDuration: { min: 30, max: 45 },
    },
    firstMonth: {
      medicineAdherence: { min: 90, max: 98 },
      physiotherapyAdherence: { min: 80, max: 92 },
      exerciseAdherence: { min: 75, max: 90 },
      appetite: "Good",
      mood: "Positive",
      sleep: { min: 7, max: 9 },
      bloodPressure: { systolicMin: 115, systolicMax: 135, diastolicMin: 72, diastolicMax: 84 },
      heartRate: { min: 62, max: 82 },
      oxygenSaturation: { min: 97, max: 99 },
      bloodSugar: { min: 82, max: 132 },
      physiotherapyAttendance: { min: 82, max: 95 },
      averageSessionDuration: { min: 40, max: 55 },
    },
    sixMonths: {
      medicineAdherence: { min: 92, max: 99 },
      physiotherapyAdherence: { min: 85, max: 96 },
      exerciseAdherence: { min: 82, max: 95 },
      appetite: "Good",
      mood: "Positive",
      sleep: { min: 7, max: 9 },
      bloodPressure: { systolicMin: 110, systolicMax: 130, diastolicMin: 68, diastolicMax: 82 },
      heartRate: { min: 60, max: 80 },
      oxygenSaturation: { min: 97, max: 100 },
      bloodSugar: { min: 80, max: 125 },
      physiotherapyAttendance: { min: 88, max: 98 },
      averageSessionDuration: { min: 45, max: 60 },
    },
    oneYear: {
      medicineAdherence: { min: 94, max: 99 },
      physiotherapyAdherence: { min: 88, max: 98 },
      exerciseAdherence: { min: 85, max: 96 },
      appetite: "Good",
      mood: "Positive",
      sleep: { min: 7, max: 9 },
      bloodPressure: { systolicMin: 108, systolicMax: 128, diastolicMin: 68, diastolicMax: 80 },
      heartRate: { min: 58, max: 78 },
      oxygenSaturation: { min: 98, max: 100 },
      bloodSugar: { min: 78, max: 120 },
      physiotherapyAttendance: { min: 90, max: 99 },
      averageSessionDuration: { min: 45, max: 60 },
    },
  },
};

export { recoveryCurves };
